force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/log_message__c.field-meta.xml
<CustomField>
    <fullName>log_message__c</fullName>
    <label>log_message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/quiddity__c.field-meta.xml
<CustomField>
    <fullName>quiddity__c</fullName>
    <label>quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/request_id__c.field-meta.xml
<CustomField>
    <fullName>request_id__c</fullName>
    <label>request_id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogMessage.cls
public with sharing class LogMessage {

    public LogMessage(String message){
        this.logMessage = message;
    }

    public LogMessage(Exception ex){
        this.logMessage = ex.getMessage() + '\n' + ex.getStackTraceString();
    }

    public String requestId {
        get {
            requestId = Request.getCurrent().getRequestId();
            return requestId;
        }
        set;
    }

    public String quiddity {
        get {
            quiddity = Request.getCurrent().getQuiddity().name();
            return quiddity;
        }
        set;
    }

    public String logMessage {get; set;}

    public Log__e convertToPlatformEvent(){
        return new Log__e(
            request_id__c = requestId,
            quiddity__c = quiddity,
            log_message__c = logMessage
        );
    }

    
}